### ISSUE TITLE
in the hactoberfest website it is saying the project is not participating

### ISSUE THREAD

**Issue by avyayjain** [surya0180/Fun_With_Python#4]

**Comment by surya0180** [comment]
hi avyay!
Unfortunately i registered into hacktoberfest as a participant only, and I was not aware of it untill one of my peer noticed it and bought it to my attention. He/She must register as a maintainer as well to make others contribute to their repo's. 

Hope this clarifies the issue

**Comment by surya0180** [comment]
Nonetheless, Your contribution was amazing and I like it personally 🙌✨.
